version: '3'

services:
  kafkadrop:
    image: obsidiandynamics/kafdrop
    container_name: kafkadrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      - "kafka"
